package com.futo.themecreator.data

import android.net.Uri

/**
 * يولّد theme.txt بصيغة FUTO Keyboard الرسمية (v1.0).
 *
 * الميزات:
 *  - ألوان HEX
 *  - الخط (إن وُجد) في [options.font]
 *  - الخلفية (إن وُجدت) في [options.background]
 *  - [[matchrules.border]] و [[matchrules.icon]] لكل صورة مخصصة
 *  - [[asset.border]] مع slicing/gap/padding/tints
 *  - [[asset.icon]] للأيقونات
 */
object TomlGenerator {

    fun generate(
        theme: ThemeData,
        icons: Map<String, Uri> = emptyMap(),
        shapeFiles: Set<String> = emptySet(),
        backgroundName: String? = null,
    ): String {
        val sb = StringBuilder()

        // ─── الترويسة ───
        sb.appendLine("# FUTO Keyboard Theme Configuration")
        sb.appendLine("# Format version: 1.0")
        sb.appendLine("# Generated by FUTO Theme Creator")
        sb.appendLine()

        // ─── معلومات أساسية ───
        sb.appendLine("name = \"${esc(theme.name)}\"")
        sb.appendLine("author = \"${esc(theme.author)}\"")
        sb.appendLine("id = \"${esc(theme.id)}\"")
        sb.appendLine("version = ${theme.version}")
        sb.appendLine("description = \"${esc(theme.description)}\"")
        sb.appendLine()

        // ─── [options] ───
        sb.appendLine("[options]")
        sb.appendLine("auto_borders = ${theme.autoBorders}")
        sb.appendLine("center_hints = ${theme.centerHints}")
        sb.appendLine("roundedness = ${theme.roundedness}")
        sb.appendLine("scale_text = ${theme.scaleText}")
        sb.appendLine("scale_hints = ${theme.scaleHints}")
        sb.appendLine("weight_text = ${theme.weightText}")
        sb.appendLine("weight_hints = ${theme.weightHints}")
        sb.appendLine()

        // ─── [options.font] ───
        theme.fontName?.let { font ->
            sb.appendLine("[options.font]")
            sb.appendLine("font = \"$font\"")
            sb.appendLine()
        }

        // ─── [options.background] ───
        if (backgroundName != null) {
            sb.appendLine("[options.background]")
            sb.appendLine("image = \"$backgroundName\"")
            sb.appendLine("opacity = ${theme.backgroundImageOpacity}")
            sb.appendLine("action_bar_opacity = ${theme.backgroundActionBarOpacity}")
            sb.appendLine("cropping = [0.0, 0.0, 1.0, 1.0]")
            sb.appendLine()
        }

        // ─── [colors] ───
        sb.appendLine("[colors]")
        theme.allColors().forEach { (k, v) ->
            sb.appendLine("$k = \"$v\"")
        }
        sb.appendLine()

        // ─── [[matchrules.border]] ───
        val borderAssets = ButtonAssets.BORDERS
        if (borderAssets.isNotEmpty()) {
            borderAssets.forEach { asset ->
                sb.appendLine("[[matchrules.border]]")
                sb.appendLine("selector = \"${asset.selector}\"")
                sb.appendLine("asset = \"${asset.fileName}\"")
                sb.appendLine()
            }
        }

        // ─── [[matchrules.icon]] ───
        val iconAssets = ButtonAssets.ICONS
        if (iconAssets.isNotEmpty()) {
            iconAssets.forEach { asset ->
                sb.appendLine("[[matchrules.icon]]")
                sb.appendLine("selector = \"${asset.selector}\"")
                sb.appendLine("asset = \"${asset.fileName}\"")
                sb.appendLine()
            }
        }

        // ─── [[asset.border]] ───
        borderAssets.forEach { asset ->
            sb.appendLine("[[asset.border]]")
            sb.appendLine("name = \"${asset.fileName}\"")
            sb.appendLine("background_tint = \"${asset.bgTint}\"")
            sb.appendLine("foreground_tint = \"${asset.fgTint}\"")
            sb.appendLine("padding = [${asset.padding.joinToString(", ")}]")
            sb.appendLine("slicing = [${asset.slicing.joinToString(", ")}]")
            sb.appendLine("gap = [${asset.gap.joinToString(", ")}]")
            sb.appendLine("target_density = 640")
            sb.appendLine()
        }

        // ─── [[asset.icon]] ───
        iconAssets.forEach { asset ->
            sb.appendLine("[[asset.icon]]")
            sb.appendLine("name = \"${asset.fileName}\"")
            sb.appendLine("target_density = 640")
            sb.appendLine()
        }

        return sb.toString()
    }

    private fun esc(s: String): String =
        s.replace("\\", "\\\\").replace("\"", "\\\"")
}
